import {Command, Flags} from '@oclif/core'
import {requireOrch} from '../lib/orch/index.js'
import {execa} from 'execa'
import fs from 'node:fs'
import path from 'node:path'

export default class Export extends Command {
  static description = 'Export the integrated project as a zip, patch, or GitHub PR'

  static examples = [
    '<%= config.bin %> export',
    '<%= config.bin %> export --zip',
    '<%= config.bin %> export --pr',
    '<%= config.bin %> export --branch my-feature',
  ]

  static flags = {
    zip: Flags.boolean({description: 'Export as a zip archive'}),
    pr: Flags.boolean({description: 'Create a GitHub Pull Request (requires gh CLI)'}),
    patch: Flags.boolean({description: 'Export as a git patch file'}),
    branch: Flags.string({description: 'Source branch (default: integration)', default: 'integration'}),
    output: Flags.string({char: 'o', description: 'Output path/name'}),
  }

  async run(): Promise<void> {
    const {flags} = await this.parse(Export)
    const {orch, root} = requireOrch()

    const plan = orch.readPlan()
    const projectName = plan?.project ?? 'metaclide-project'

    if (flags.zip) {
      await this.exportZip(root, projectName, flags.branch, flags.output)
    } else if (flags.pr) {
      await this.createPR(root, projectName, flags.branch)
    } else if (flags.patch) {
      await this.exportPatch(root, flags.branch, flags.output)
    } else {
      // Default: show summary
      this.log('Export options:')
      this.log('  --zip    Export as zip archive')
      this.log('  --pr     Create GitHub Pull Request')
      this.log('  --patch  Export as git patch')
      this.log('')
      this.log(`Current integration branch: ${flags.branch}`)

      if (fs.existsSync(path.join(root, '.orch', 'integration-report.md'))) {
        this.log('')
        this.log('Integration report:')
        this.log(fs.readFileSync(path.join(root, '.orch', 'integration-report.md'), 'utf8'))
      }
    }
  }

  private async exportZip(root: string, name: string, branch: string, output?: string): Promise<void> {
    const outFile = output ?? `${name}.zip`
    try {
      await execa('git', ['archive', '--format=zip', `--output=${outFile}`, branch], {cwd: root})
      this.log(`Exported: ${outFile}`)
    } catch (err) {
      this.error(`Failed to create zip: ${err}`)
    }
  }

  private async createPR(root: string, name: string, branch: string): Promise<void> {
    try {
      const report = fs.existsSync(path.join(root, '.orch', 'integration-report.md'))
        ? fs.readFileSync(path.join(root, '.orch', 'integration-report.md'), 'utf8')
        : ''

      const body = `## MetaCLiDE Generated Project\n\n${report}\n\n🤖 Generated by [MetaCLiDE](https://github.com/metaclide/metaclide)`

      const result = await execa('gh', [
        'pr', 'create',
        '--title', `feat: ${name} (MetaCLiDE)`,
        '--body', body,
        '--head', branch,
      ], {cwd: root})

      this.log(`Pull request created: ${result.stdout}`)
    } catch (err) {
      this.error(`Failed to create PR. Ensure 'gh' CLI is installed and authenticated.\n${err}`)
    }
  }

  private async exportPatch(root: string, branch: string, output?: string): Promise<void> {
    const outFile = output ?? `metaclide-${branch}.patch`
    try {
      const {stdout} = await execa('git', ['format-patch', 'main', '--stdout', branch], {cwd: root})
      fs.writeFileSync(outFile, stdout)
      this.log(`Exported patch: ${outFile}`)
    } catch (err) {
      this.error(`Failed to create patch: ${err}`)
    }
  }
}
